### ISSUE TITLE
Emojiler birden fazla gorunuyor

### ISSUE THREAD

**Issue by hasanakg** [nicefella/eksiifadeler#2]
Emojiler daha onceden oy verilmis olsa da birden fazla gorunuyor. Bu sorun icin PR actim. #1

**Comment by nicefella** [comment]
#1 ı henüz inceleyebildim. Bence böyle muhteşem oldu. Emeğinize sağlık! Merge ettim. Yeni sürümü de publish edeceğim bugün içinde.
